import = ["/home/able/.config/alacritty/themes/campbell.toml"]

[font]
size = 14

[font.normal]
family = "SourceCodePro"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "J"
mods = "Control|Shift"

[scrolling]
history = 10000
multiplier = 5
